name: Deploy Firebase
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy_firebase:
    name: Deploy Firebase
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2
        with:
          node-version-file: 16
          cache: npm
      - name: Install Dependencies
        run: npm ci
      - name: Build Firebase Functions
        run: npm run build:functions
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --except hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
